### ISSUE TITLE
AWS Supported Kubernetes Documentation

### ISSUE THREAD

**Issue by cyberious** [Kong/kong-dist-kubernetes#20]
Would like to see some cloud provider agnostic docs or additional info doing either.

**Comment by chandresh-pancholi** [comment]
+1

**Comment by stackedsax** [comment]
@cyberious I agree, having that second step of "Deploy a GKE cluster" makes it seem weirdly GKE-specific, which isn't the case.

Personally, I think all of the "stuff" in the root of this project should just go away in favor of the helm chart that @shashiranjan84 and @lawrencegripper put together.  If that were the case and there was no provider-specific directions, would that make sense to you?

**Comment by chrisdiaz0** [comment]
@cyberious I've had a quick look online and I don't fully understand the purpose of the helm chart. Is this supposed to make it easy to deploy a k8s cluster in a cloud provider? e.g. AWS EC2 instances.

If so, how is this different than KOPS? Or are helm charts just another way to configure the k8s cluster and/or nodes/services?

I know, lot's of questions, any clarity would be much appreciated.

**Comment by coopr** [comment]
Our documentation at https://docs.konghq.com/install/kubernetes/ has expanded to cover more installation options. 

I'll close this issue now - we try to keep Github Issues for bug reports. For questions, feature suggestions, docs suggestions, etc, please post to https://discuss.konghq.com/c/kubernetes
