### ISSUE TITLE
error validating "cassandra.yaml"

### ISSUE THREAD

**Issue by elipapa** [Kong/kong-dist-kubernetes#24]
When executing 

`kubectl create -f cassandra.yaml`

on a GKE cluster I get the following error:
```sh
error validating "cassandra.yaml": error validating data: the server could not find the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by stackedsax** [comment]
Hey there @elipapa  -- this chart made some improvements and now pulls in the official cassandra chart from helm/charts, so this should no longer be an issue.  Can you retest?

**Comment by shashiranjan84** [comment]
https://hub.kubeapps.com/charts/stable/kong
