### ISSUE TITLE
Kong Admin port does not work 

### ISSUE THREAD

**Issue by prateek2408** [Kong/kong-dist-kubernetes#46]
The kong admin port and admin ssl port is listening to 127.0.0.1 instead of 0.0.0.0 due to which access of admin port from K8S loadbalancer is service is not possible. Connection  is refused at kubernetes level

>  
> ================================================================
> [root@sandbox-controller-sec kong-dist-kubernetes]# kubectl get svc --all-namespaces=true
> NAMESPACE     NAME             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
> default       kong-admin       LoadBalancer   10.101.32.176    <pending>     8001:32601/TCP   18s
> default       kong-admin-ssl   LoadBalancer   10.101.95.182    <pending>     8444:32224/TCP   18s
> default       kong-proxy       LoadBalancer   10.104.106.80    <pending>     8000:30682/TCP   18s
> default       kong-proxy-ssl   LoadBalancer   10.102.116.170   <pending>     8443:30701/TCP   18s
> default       kubernetes       ClusterIP      10.96.0.1        <none>        443/TCP          1d
> default       postgres         ClusterIP      10.96.82.10      <none>        5432/TCP         4m
> kube-system   kube-dns         ClusterIP      10.96.0.10       <none>        53/UDP,53/TCP    1d
> [root@sandbox-controller-sec kong-dist-kubernetes]# telnet 10.101.32.176 8001
> Trying 10.101.32.176...
> telnet: connect to address 10.101.32.176: Connection refused
> [root@sandbox-controller-sec kong-dist-kubernetes]# telnet 10.101.32.176 8001
> Trying 10.101.32.176...
> telnet: connect to address 10.101.32.176: Connection refused
> [root@sandbox-controller-sec kong-dist-kubernetes]# telnet 10.104.106.80 8000
> Trying 10.104.106.80...
> Connected to 10.104.106.80.
> Escape character is '^]'.
> ^]
> telnet> quit
> Connection closed.
> [root@sandbox-controller-sec kong-dist-kubernetes]# telnet 10.101.32.176 8001
> Trying 10.101.32.176...
> telnet: connect to address 10.101.32.176: Connection refused
> **[root@sandbox-controller-sec kong-dist-kubernetes]# telnet 10.101.32.176 8001
> Trying 10.101.32.176...
> telnet: connect to address 10.101.32.176: Connection refused**
> 
> ================================================================
> 
> 

When Kong is started it uses 127.0.0.1 for admin port by default-

> 
> [root@kong-rc-76b9cf6fc5-dvsv8 kong]# kong start -vvv 
> 2018/01/18 15:00:40 [verbose] Kong: 0.12.0
> 2018/01/18 15:00:40 [verbose] reading config file at /opt/confg/nginx/nginx.conf
> 2018/01/18 15:00:40 [verbose] prefix in use: /opt/confg/kong
> 2018/01/18 15:00:40 [verbose] preparing nginx prefix directory at /opt/confg/kong
> 2018/01/18 15:00:40 [verbose] SSL enabled, no custom certificate set: using default certificate
> 2018/01/18 15:00:40 [verbose] default SSL certificate found at /opt/confg/kong/ssl/kong-default.crt
> 2018/01/18 15:00:40 [verbose] Admin SSL enabled, no custom certificate set: using default certificate
> 2018/01/18 15:00:40 [verbose] admin SSL certificate found at /opt/confg/kong/ssl/admin-kong-default.crt
> 2018/01/18 15:00:43 [verbose] could not start Kong, stopping services
> 2018/01/18 15:00:43 [verbose] stopped services
> Error:
>   sr/local/share/lua/5.1/kong/cmd/start.lua:62: /usr/local/share/lua/5.1/kong/cmd/start.lua:51: nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use▒
> nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
> nginx: [emerg] bind() to 127.0.0.1:8001 failed (98: Address already in use)
> nginx: [emerg] bind() to 127.0.0.1:8444 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
> nginx: [emerg] bind() to **127.0.0.1:8001** failed (98: Address already in use)
> nginx: [emerg] bind() to 127.0.0.1:8444 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
> nginx: [emerg] bind() to **127.0.0.1:8001** failed (98: Address already in use)
> nginx: [emerg] bind() to 127.0.0.1:8444 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
> nginx: [emerg] bind() to 127.0.0.1:8001 failed (98: Address already in use)
> nginx: [emerg] bind() to 127.0.0.1:8444 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:8000 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:8443 failed (98: Address already in use)
> nginx: [emerg] bind() to 127.0.0.1:8001 failed (98: Address already in use)
> nginx: [emerg] bind() to 127.0.0.1:8444 failed (98: Address already in use)
> 
> [root@kong-rc-76b9cf6fc5-dvsv8 /]# netstat -anp
> Active Internet connections (servers and established)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
> tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      1/nginx: master pro
> tcp        0      0 127.0.0.1:8444          0.0.0.0:*               LISTEN      1/nginx: master pro
> tcp        0      0 0.0.0.0:8000            0.0.0.0:*               LISTEN      1/nginx: master pro
> tcp        0      0 **127.0.0.1:8001**          0.0.0.0:*               LISTEN      1/nginx: master pro**
> 
> 

A workaround is to add  **admin_listen=0.0.0.0:8001** in the kong configuration before starting

Ideally it should use 0.0.0.0

**Comment by Tieske** [comment]
we're in the process of updating this since 0.12.0 was released (where the default was changed).

Using 0.0.0.0 would be bad as a default. Very unsecure, hence we changed it.

**Comment by prateek2408** [comment]
But in that case we wont be able to access it from service endpoints of K8S.

I agree that 0.0.0.0 is insecure but in that at least there should be some environment variables which I can set in the kubernetes Yaml while deployment so it can be changed.

**Comment by shashiranjan84** [comment]
@prateek2408 you do have option to set env variables in manifest file. If you using chart then just set `Values.kong.customConfig` with all the custom envs.

**Comment by prateek2408** [comment]
@shashiranjan84 - Using custom Config and specifying environment variables worked for me. Thanks

We should add this in the readme of the kong-kubernetes-dist GIT repo

**Comment by dsnr-pavankumar** [comment]
Could you please tell me in which kong tag name the above is fixed, so that I will take previous version
