### ISSUE TITLE
How can I add custom plugins?

### ISSUE THREAD

**Issue by imatefx** [Kong/kong-dist-kubernetes#48]
I am wondering how to add custom plugin to a kong installed on kubernetes

**Comment by shashiranjan84** [comment]
One way would be to customize the manifest file to download the custom plugin in command section, install it in the container and start kong with `KONG_CUSTOM_CONFIGURATIONS` set.

**Comment by shashiranjan84** [comment]
You can also work with your custom docker image for Kong with side loaded Kong plugins.

**Comment by FraBle** [comment]
@shashiranjan84 Can you share some more details on how to achieve it with `KONG_CUSTOM_PLUGINS`?

**Comment by shashiranjan84** [comment]
@FraBle you can deploy you custom plugin on Lucrocks and install it into the container while provisioning the container. To enable the plugin you would to set  `KONG_PLUGINS` env.  Please check this configuration guide https://docs.konghq.com/0.14.x/configuration/#plugins and this plugin development guide https://docs.konghq.com/0.14.x/plugin-development/.

**Comment by FraBle** [comment]
Thank you very much! I will check out the resource!
