### ISSUE TITLE
Very long readinessProbe

### ISSUE THREAD

**Issue by rchernobelskiy** [Kong/kong-dist-kubernetes#49]
Hi Shashi, thank you for creating the kong chart.
I was wondering, why is the readinessProbe initial delay set to 300 seconds (5 minutes)?
Is there a reason that it needs to be so long?

**Comment by shashiranjan84** [comment]
Frankly is't not profiled, I just put enough time for Kong to wait before Postgres and migrations pods are up. I will update it to more appropriate value.
