### ISSUE TITLE
Support for bare metal Kubernetes cluster

### ISSUE THREAD

**Issue by robertrbruno** [Kong/kong-dist-kubernetes#58]
Please correct me if I am wrong, but Kong currently will not work on a Kubernetes bare metal cluster due to the lack of LoadBalancer services.  It seems LoadBalancer services are a dependency.  If not are there Kubernetes configs available for a bare metal cluster?

**Comment by shashiranjan84** [comment]
You can use `Nodeport`. Try using manifest files defined in minikube directory.
