### ISSUE TITLE
Error when setting up kong on minikube {"message":"no route and no API found with those values"}

### ISSUE THREAD

**Issue by omarwqureshi** [Kong/kong-dist-kubernetes#59]
I am currently trying to setup Kong on a minikube kubernetes cluster, and I have followed the steps from https://github.com/Kong/kong-dist-kubernetes/blob/master/minikube/README.md

However, When I run the command the `curl $(minikube service --url kong-proxy|head -n1)` I get the response `{"message":"no route and no API found with those values"}`

I am unsure on why this is happening as all the pods are running and when I curl kong-admin I get the correct response.

**Comment by Tieske** [comment]
That is because you did not configure Kong itself. Kong receives your request, but doesn't know how to handle it, and hence returns this message. So this is expected behaviour.

Please walk through the Kong 5 minute quickstart, which will show you the basics of how Kong works.
