### ISSUE TITLE
Kong does not detect new ingress resource

### ISSUE THREAD

**Issue by vishpat** [Kong/kong-dist-kubernetes#61]
Kubernetes details
==============
kubectl --version
Kubernetes v1.9.5

Kong Installation
============
helm install --name kongssl stable/kong

Ingress Resource
=============
<pre>
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: ns
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - foo.bar
    secretName: foo-cert 
  rules:
  - host: foo.bar 
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000 
</pre>

Issue
====

The ingress resource gets create successfully however no new service is added to Kong

<pre>
curl -k https://ADMIN_IP:ADMIN_PORT/apis
{"total":0,"data":[]}

curl -k https://ADMIN_IP:ADMIN_PORT/services
{"next":null,"data":[]}
</pre>

**Comment by hbagdi** [comment]
Duplicated by https://github.com/Kong/kubernetes-ingress-controller/issues/108
