### ISSUE TITLE
for postgres: the migration doesn't work because the host is incorrect

### ISSUE THREAD

**Issue by nirradi** [Kong/kong-dist-kubernetes#65]
it says: 
```
 - name: KONG_PG_HOST
            value: postgres.default.svc.cluster.local
``` 
and probably should simply say "postgres" instead.

**Comment by lauer** [comment]
It works with just `postgres` as value

**Comment by hutchic** [comment]
I'm not sure what would have caused this previously to not be working but I can say for certain it's working now. Apologies the issue got missed if you're still having difficulty re-open or start a new issue
