### ISSUE TITLE
for postgres:the migration doesn't work with postgres owing multiple replicas

### ISSUE THREAD

**Issue by Zzzwenjie** [Kong/kong-dist-kubernetes#75]
I have noticed that the migration can't run successfully at environment with multiple replicas of postgres.And then i deployed a HA environment of postgres,nether can the migration run successfully.The error of  above two status are the same -----can't find postgres,finally timeout.

Is that function not supportable?

**Comment by hutchic** [comment]
As long as Kong can access a postgres database with a configured postgres user that can write to the datastore it should be fine
