### ISSUE TITLE
Unable to mount volumes for pod  when uses cassandra

### ISSUE THREAD

**Issue by majulong** [Kong/kong-dist-kubernetes#82]
the log is 
  Normal   Scheduled              2m    default-scheduler         Successfully assigned cassandra-0 to 192.168.110.131
  Normal   SuccessfulMountVolume  2m    kubelet, 192.168.110.131  MountVolume.SetUp succeeded for volume "default-token-qmqjk"
  Warning  FailedMount            14s   kubelet, 192.168.110.131  Unable to mount volumes for pod "cassandra-0_default(9a39b8ab-a9d2-11e9-bc97-000c293279b8)": timeout expired waiting for volumes to attach/mount for pod "default"/"cassandra-0". list of unattached/unmounted volumes=[cassandra-data]

**Comment by hutchic** [comment]
Our cassandra k8s yaml is lifted almost entirely from https://github.com/kubernetes/examples/tree/master/cassandra best to take your issue there.

At a glance it looks like Cassandra didn't get a volume in time from k8s.
